### ISSUE TITLE
the final_classify don't works

### ISSUE THREAD

**Issue by STEPHENSXZ** [ADlead/Dogs-Cats#1]
I changed IS_TRAIN to Flse and delete the last comment, but it seems that the final_classify function doesn't work, I can't find the classified file.
 Am i wrong somewhere? hoping to receive your reply! thank you!

**Comment by STEPHENSXZ** [comment]
sorry  I have solved the problem! thank you so much!

**Comment by ADlead** [comment]
Sorry that I am busy these days and didn't check my email.
Since you have solved your problems, that's great.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"STEPHENSXZ"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月18日(星期三) 凌晨3:31
收件人:&nbsp;"ADlead/Dogs-Cats"<Dogs-Cats@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [ADlead/Dogs-Cats] the final_classify don't works (#1)





 
sorry  I have solved the problem! thank you so much!
